### ISSUE TITLE
Can't send more than 99999 kB3 in single transaction

### ISSUE THREAD

**Issue by ThunderousDreamer** [B3-Coin/B3-CoinV2#48]
Sending in wallet doesn't allow for number than 99999 kB3. If I want to send more than than (say 100k kb3), I have to change display option to B3 before I can send.

**Comment by rohingosling** [comment]
I get this too, on my local wallet that I run on my Windows laptop. But all the FN wallets that I run on Windows VPSs, all seem not have this issue. Which makes me wonder if it could be a formatting issue associated with Windows location settings. If so, there may be a temporary work around  by setting something in Windows location settings.

**Comment by SanSaiSolutions** [comment]
Same here. Changing decimal separator in Windows regional settings does not help.

**Comment by joshafest** [comment]
resolved I guess? reopen if again encountered

**Comment by SanShiner** [comment]
No its not resolved. 
Why you closed it because of guessing? Should be closed based on facts. No point to reopen anything here... no actions taken for +1 year and then even closed issue.. huh

**Comment by joshafest** [comment]
this resolved it.
